// app/app.component.ts
import {Component, OnInit, Inject} from '@angular/core';
import {ROUTER_DIRECTIVES} from '@angular/router';

import {UsersActions} from './pantry-list/users.actions';
import {ItemsActions} from './pantry-list/items.actions';
import {STORE_TOKEN} from './config/create-store';

@Component({
    selector: 'my-app',
    template: `
        <ul class="nav nav-tabs">
            <li><a [routerLink]="['/']" routerLinkActive="active">List</a></li>
            <li><a [routerLink]="['/stats']" routerLinkActive="active">Stats</a></li>
        </ul>
        <router-outlet></router-outlet>
    `,
    directives: [ROUTER_DIRECTIVES],
    providers: [UsersActions, ItemsActions],
})
export class AppComponent implements OnInit {

    constructor(
        @Inject(STORE_TOKEN) private store: any,
        private itemsActions: ItemsActions,
        private usersActions: UsersActions
    ) {}

    ngOnInit() {
        // load this data here as they are needed for both pages
        this.store.dispatch(this.usersActions.loadUsers());
        this.store.dispatch(this.usersActions.loadCurrentUserId());
        this.store.dispatch(this.itemsActions.loadItems());
    }
}

// app/app.component.tsx
import * as React from 'react';
import {connect} from 'react-redux';
import {Link} from 'react-router';

import {loadUsers, loadCurrentUserId} from './users/users.actions';
import {loadItems} from './pantry-list/items.actions';


type Props = {
    children: any,
    loadItems: Function,
    loadUsers: Function,
    loadCurrentUserId: Function
};
class AppComponent extends React.Component<Props, any> {
    props: Props;

    componentWillMount() {
        this.props.loadItems();
        this.props.loadUsers();
        this.props.loadCurrentUserId();
    }

    render() {
        const {children} = this.props;

        return (
            <div className="app">
                <ul className="nav nav-tabs">
                    <li>
                        <Link to={`/`}>
                            List
                        </Link>
                    </li>
                    <li>
                        <Link to={`/stats`}>
                            Stats
                        </Link>
                    </li>
                </ul>
                {children}
            </div>
        );
    }
}

// we are just loading data, children components will select state
function mapStateToProps(state) {
    return {};
}

function mapDispatchToProps(dispatch) {
    return {
        loadItems: () => dispatch(loadItems()),
        loadUsers: () => dispatch(loadUsers()),
        loadCurrentUserId: () => dispatch(loadCurrentUserId()),
    };
}


export default connect(mapStateToProps, mapDispatchToProps)(AppComponent);
