// app/pantry-list/pantry-list.component.tsx
import * as React from 'react';
const cx = require('classnames');

type Props = {
    users: any[],
    currentUserId: number,
    items: any[],
    takeItem: Function,
}
type State = {
    showSelectItemError: boolean,
    selectedItemId: number,
    selectedUserId: number,
}
export default class PantryListComponent extends React.Component<Props, State> {
    props: Props;
    state: State;

    constructor(props) {
        super(props);
        this.state = {
            showSelectItemError: false,
            selectedItemId: null,
            selectedUserId: this.props.currentUserId || (this.props.users.length && this.props.users[0].id),
        };
    }

    componentWillReceiveProps(nextProps) {
        if (!this.props.currentUserId && nextProps.currentUserId) {
            // current user was loaded from the server
            this.setState({
                selectedUserId: nextProps.currentUserId,
            });
        }

        if (this.props.users.length !== nextProps.users.length && !this.state.selectedUserId) {
            // select first user from users if not already selected, if current user comes later, it will take
            // precedence
            this.setState({
                selectedUserId: nextProps.users[0].id,
            });
        }
    }

    render() {

        return (
            <div className="pantry-list">
                <h1>Pantry</h1>
                <form onSubmit={(e) => this.onSubmit(e)}>
                    {this.props.items ?
                        <div className="list-group">
                            {this.props.items.map(item =>
                                <label
                                    className={cx('list-group-item', {disabled: item.count === 0})}
                                    key={item.id}
                                >
                                    <input
                                        type="radio"
                                        name="pantry_item"
                                        checked={item.id === this.state.selectedItemId}
                                        onChange={(event) => {
                                            if (event.target.checked) {
                                                this.setState({
                                                    showSelectItemError: false,
                                                    selectedItemId: item.id,
                                                });
                                            }
                                        }}
                                        disabled={item.count === 0}
                                    />
                                    &nbsp;
                                    {item.name}
                                    <span className="badge">{item.count} left</span>
                                </label>
                            )}
                        </div> : null
                    }

                    {this.state.showSelectItemError ?
                        <div className="alert alert-danger">
                            You need to select a snack to take.
                        </div> : null
                    }

                    <div className="form-group bottom">
                        {this.props.users ?
                            <select
                                className="form-control"
                                required
                                value={this.state.selectedUserId}
                                onChange={(event) => this.setState({selectedUserId: event.target.value})}
                                name="user_id"
                            >
                                {this.props.users.map(user =>
                                    <option
                                        value={user.id}
                                        key={user.id}
                                    >
                                        {user.name}
                                    </option>
                                )}
                            </select> : null
                        }
                        <button type="submit" className="btn btn-primary">Take a snack</button>
                    </div>
                </form>
            </div>
        );
    }

    onSubmit(event) {
        event.preventDefault();
        if (this.state.selectedItemId === null) {
            this.setState({showSelectItemError: true});
            return;
        }

        this.props.takeItem(this.state.selectedItemId, this.state.selectedUserId)
            .then(() => this.setState({selectedItemId: null}));
    }
}

// app/pantry-list/pantry-list.component.ts
import { Component, OnInit } from '@angular/core';

import { UserService } from '../user.service';
import { PantryService } from '../pantry.service';

@Component({
    selector: 'pantry-items',
    template: `
        <h1>Pantry</h1>
        <form (ngSubmit)="onSubmit()">
        
            <div *ngIf="pantryItems">
                <ul>
                    <li *ngFor="let item of pantryItems">
                        <input
                            type="radio"
                            name="pantry_item"
                            value="{{item.id}}"
                            [(ngModel)]="selectedItemId"
                            (click)="clearItemError()"
                        />
                        {{item.name}}
                    </li>
                </ul>
            </div>
            <div *ngIf="showItemRequired" class="error-message">
                You need to select a snack to take.
            </div>
        
            <div class="form-group">
                <select
                    class="form-control"
                    required
                    [(ngModel)]="selectedUserId"
                    [ngModelOptions]="{standalone: true}"
                    name="user_id"
                >
                    <option *ngFor="let user of users" [value]="user.id">
                        {{user.name}}
                    </option>
                </select>
            </div>
            <button type="submit" class="btn btn-default">Take a snack</button>
            {{selectedItemId}}
        </form>
    `,
    providers: [UserService, PantryService]
})
export class PantryListComponent implements OnInit {
    pantryItems: Object[];
    // initialize so we do not have to handle empty state in template by hiding something
    users: Object[] = [];

    selectedUserId: number;
    selectedItemId: number;
    showItemRequired = false;

    constructor(
        private userService: UserService,
        private pantryService: PantryService
    ) {}

    ngOnInit() {
        this.pantryService.getItems().then(items => this.pantryItems = items);
        this.userService
            .getUsers()
            .then(users => {
                this.users = users;
                // TODO init from session
                this.selectedUserId = users[0].id;
            });
    }

    getPantryItems() {
        return [];
    }

    clearItemError() {
        this.showItemRequired = false;
    }

    onSubmit() {
        if (!this.selectedItemId) {
            this.showItemRequired = true;
            return;
        }
        console.log('submit');
    }
}


<h1>Pantry</h1>
<form (ngSubmit)="onSubmit()">

    <div *ngIf="pantryItems">
        <ul class="list-group">
            <label *ngFor="let item of pantryItems" class="list-group-item" [class.disabled]="item.count == 0">
                <input
                    type="radio"
                    name="pantry_item"
                    value="{{item.id}}"
                    [(ngModel)]="selectedItemId"
                    (click)="clearItemError()"
                    [disabled]="item.count == 0"
                />
                {{item.name}}

                <span class="badge">{{item.count}} left</span>
            </label>
        </ul>
    </div>
    <div *ngIf="showItemRequired" class="alert alert-danger">
        You need to select a snack to take.
    </div>

    <div class="form-group bottom" *ngIf="users">
        <select
            class="form-control"
            required
            [(ngModel)]="selectedUserId"
            [ngModelOptions]="{standalone: true}"
            name="user_id"
        >
            <option *ngFor="let user of users" [value]="user.id">
                {{user.name}}
            </option>
        </select>
        <button type="submit" class="btn btn-primary">Take a snack</button>
    </div>
</form>
